CREATE TABLE [PERSONA].[ASIGNACION]
(
[IDASIG] [int] NOT NULL IDENTITY(1, 1),
[IDPERJEF] [int] NULL,
[IDSUC] [int] NULL,
[ESTAASIGPER] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [PERSONA].[ASIGNACION] ADD CONSTRAINT [PK__ASIGNACI__1D0F8382356587ED] PRIMARY KEY CLUSTERED  ([IDASIG]) ON [PRIMARY]
GO
ALTER TABLE [PERSONA].[ASIGNACION] ADD CONSTRAINT [PERSONA_ASIGNACION_IDPERJEF] FOREIGN KEY ([IDPERJEF]) REFERENCES [PERSONA].[PERSONA] ([IDPER])
GO
ALTER TABLE [PERSONA].[ASIGNACION] ADD CONSTRAINT [SUCURSAL_ASIGNACION_IDSUC] FOREIGN KEY ([IDSUC]) REFERENCES [UBICACION].[SUCURSAL] ([IDSUC])
GO
