CREATE TABLE [PERSONA].[DETALLE_ASIGNACION]
(
[IDDETASIG] [int] NOT NULL IDENTITY(1, 1),
[IDASIG] [int] NULL,
[IDPEREMP] [int] NULL,
[ESTADETASIG] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [PERSONA].[DETALLE_ASIGNACION] ADD CONSTRAINT [PK__DETALLE___C2F17EB65D022945] PRIMARY KEY CLUSTERED  ([IDDETASIG]) ON [PRIMARY]
GO
ALTER TABLE [PERSONA].[DETALLE_ASIGNACION] ADD CONSTRAINT [ASIGNACION_DETALLE_ASIGNACION_IDASIG] FOREIGN KEY ([IDASIG]) REFERENCES [PERSONA].[ASIGNACION] ([IDASIG])
GO
ALTER TABLE [PERSONA].[DETALLE_ASIGNACION] ADD CONSTRAINT [PERSONA_DETALLE_ASIGNACION_IDPEREMP] FOREIGN KEY ([IDPEREMP]) REFERENCES [PERSONA].[PERSONA] ([IDPER])
GO
