CREATE TABLE [PERSONA].[PERSONA]
(
[IDPER] [int] NOT NULL IDENTITY(1, 1),
[NOMPER] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEPER] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DNIPER] [char] (9) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TIPPER] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PSWPER] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTAPER] [char] (6) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [PERSONA].[PERSONA] ADD CONSTRAINT [PK__PERSONA__98FE8B7E791F7D1E] PRIMARY KEY CLUSTERED  ([IDPER]) ON [PRIMARY]
GO
