CREATE TABLE [PRODUCTO].[INVENTARIO]
(
[IDINV] [int] NOT NULL IDENTITY(1, 1),
[IDEQUI] [int] NULL,
[FECINV] [date] NULL,
[CANTINV] [int] NULL,
[TIPINV] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDSUC] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [PRODUCTO].[INVENTARIO] ADD CONSTRAINT [EQUIPO_INVENTARIO_IDEQUI] FOREIGN KEY ([IDEQUI]) REFERENCES [PRODUCTO].[EQUIPO] ([IDEQUI])
GO
