CREATE TABLE [PRODUCTO].[EQUIPO]
(
[IDEQUI] [int] NOT NULL IDENTITY(1, 1),
[DESEQUI] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[PREEQUI] [decimal] (7, 2) NULL,
[ESTAEQUI] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [PRODUCTO].[EQUIPO] ADD CONSTRAINT [PK__EQUIPO__3C5A119203B6A39B] PRIMARY KEY CLUSTERED  ([IDEQUI]) ON [PRIMARY]
GO
