CREATE TABLE [UBICACION].[SUCURSAL]
(
[IDSUC] [int] NOT NULL IDENTITY(1, 1),
[NOMSUC] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[ESTASUC] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [UBICACION].[SUCURSAL] ADD CONSTRAINT [PK__SUCURSAL__A5C81E91EFBCE75F] PRIMARY KEY CLUSTERED  ([IDSUC]) ON [PRIMARY]
GO
