CREATE TABLE [VENTA].[DETALLE_VENTA]
(
[IDDETVENT] [int] NOT NULL IDENTITY(1, 1),
[IDVENT] [int] NULL,
[IDEQUI] [int] NULL,
[CANTEQUI] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[DETALLE_VENTA] ADD CONSTRAINT [PK__DETALLE___B14554A8ADF6BCD8] PRIMARY KEY CLUSTERED  ([IDDETVENT]) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[DETALLE_VENTA] ADD CONSTRAINT [EQUIPO_DETALLE_VENTA_IDEQUI] FOREIGN KEY ([IDEQUI]) REFERENCES [PRODUCTO].[EQUIPO] ([IDEQUI])
GO
ALTER TABLE [VENTA].[DETALLE_VENTA] ADD CONSTRAINT [VENTA_DETALLE_VENTA_IDVENT] FOREIGN KEY ([IDVENT]) REFERENCES [VENTA].[VENTA] ([IDVENT])
GO
